---
- name: start some services
  hosts: web
  vars:
    my_services:
      - crond
      - sshd
  tasks:
    - name: start and stop services
      service:
        name: "{{ item }}"
        state: restarted
      loop: "{{ my_services }}"
